### PR TITLE
feat: support hugo cmd cross-platform

### LINKED ISSUE #11: [BUG, HELP WANTED]
Hugo can be installed in various ways on a number of platforms - in particular, Windows, Mac, and Linux, - and either by downloading the binary to a local folder or using a package manager such as choco or snap to install it globally, creating cross-platform NPM scripts that run Hugo is tricky. 

Currently, I've added a note to the repo saying that it might be required to adjust the `start` and `production` scripts in package.json replacing `.\\hugo`:

* `.\\hugo`: current approach, works for local install on Windows
* `./hugo`: required for local install in Mac or Linux
* `hugo`: for global install on any platform

An obvious solution is to require a global install but this makes installing Hugo trickier for people who are not familiar with package managers or editing $PATH so I would prefer to avoid this.

### PR DESCRIPTION
**Pull request by Xie-Jay**
close #11

I just test with Window

### CODE REVIEW

**Comment by Xie-Jay** [comment]
some error

**Comment by Xie-Jay** [comment]
ok now

**Comment by looeee** [comment]
Cool, that looks great now 👍 Thank you. 

I'll test it properly before I merge - either tomorrow or Monday.

**Comment by Xie-Jay** [comment]
> Cool, that looks great now  Thank you.
> 
> I'll test it properly before I merge - either tomorrow or Monday.

No rush, we should enjoy our own time :smile:

**Comment by looeee** [comment]
OK, this looks great. 

Thanks for your help ^_^

**Comment by looeee** [comment]
This should make it easy for me to build the site on the server so I've removed the `public/` folder from the repo.

**Comment by Xie-Jay** [comment]
> This should make it easy for me to build the site on the server so I've removed the `public/` folder from the repo.

@looeee maybe forget `git rm,` repo still has `public` folder, also ` static/examples/vendor/three` ^_^

**Comment by looeee** [comment]
I did! Fixed now 😅

**Pull request merged**
