### PR TITLE
feat：tips-and-tricks-CHS

### PR DESCRIPTION
**Pull request by Yenseaon**
Here is the chinese translation of "The Big List of three.js Tips and Tricks"
Sorry  I am not familiar with the Hugo, and don.t know where to  add the page.
Hope U guys can help me to do that

### CODE REVIEW

**Comment by looeee** [comment]
Hey Yenseaon, this is great. Thank you so much 🙇 

I'll do the rest of the integration. I'll need to set up some stuff in Hugo to enable translations. 

Please be patient though because it's Christmas and I'm going' on vacation in a couple of days. I'll be back on the 4th January and will give this priority once I'm back.

**Comment by Yenseaon** [comment]
Sorry to disturb your vacation and Merry Christmas~！！！:smile:

**Comment by looeee** [comment]
Sorry for the delay, I will get back to this in the next couple of days.

**Comment by looeee** [comment]
Merging this now, I will set up a system for switching pages and then push to the live site. 

Thanks again for the translation 😁

**Comment by looeee** [comment]
OK, we are live! 

Can you please check that it looks ok here?

https://discoverthreejs.com/tips-and-tricks/

Click "中文" to switch over.

**Pull request merged**
